# Generated by Django 5.0.4 on 2026-02-19

from django.contrib.auth.hashers import check_password, make_password
from django.db import migrations
from django.utils.text import slugify

TEST_USERNAME = "test"
TEST_EMAIL = "test@andrena.de"
TEST_PASSWORD = "test"
TEST_IMAGE = "/static/user_pics/test.png"
JW_USERNAME = "JW"
JW_EMAIL = "jw@andrena.de"
JW_PASSWORD = "jw"
JW_IMAGE = "/static/user_pics/image.png"

ARTICLE_SEEDS = [
    {
        "title": "Als Dev mit KI so schnell wie noch nie?",
        "description": (
            "Ein Selbsttest und warum er zur Nachahmung empfohlen ist"
        ),
        "body": """Vermutlich kennt ihr die Situation: Projekteinsatz A ist beendet, Projekteinsatz B erst in einigen Wochen und die Frage offen, für welche Weiterbildung ihr euch in der Zwischenzeit entscheidet. Das war die Ausgangslage, als ich beschloss, mich in die KI-gestützte Entwicklung einzuarbeiten. Nicht in irgendeine Form davon, sondern in den KI-Einsatz bei der Modernisierung von Bestandssystemen, formerly known als Migration.

Damit stand ich gleich vor der ersten Hürde: Ich hatte praktisch keine Erfahrung damit, mit KI-Tools Code zu erstellen, abgesehen von sehr rudimentären Experimenten mit Microsoft Copilot. Doch das ist nicht der Stand der Technik, wenn es um KI-Tools für professionelles Engineering geht. Wobei es „den" Stand der Technik ohnehin nicht gibt, weil sich das, was möglich ist, spätestens alle zwei Monate weiter nach vorne schiebt. Was meine grundlegende Frage, wie fange ich an, jedoch nicht löst.

## Der Lernkurve erster Teil: Das (kleine) ASE Frontend

Wie wir vorgehen können und mit welchen Tools, das waren daher die Fragen, die unser Migrationsteam den KI-Experten stellte. Angefangen haben wir dann damit, das ASE Frontend mit seinen ca. 10.000 lines of code (LOC) in React auf Angular zu übertragen. Verwendet haben wir folgende Tools:

- **Claude Code** (mit Claude 4.5 Sonnet)
- **OpenAI Codex** (GPT 5)
- **Kilo Code**, ein Open Source AI-Coding Assistent, der sich direkt in Editoren wie VS Code, Cursor oder JetBrains IDEs integrieren lässt und als API zu vielen verschiedenen LLMs fungieren kann (OpenAI, Anthropic, Google etc.)

> **Disclaimer:** Eine Migration ist nicht einfach eine Frage des Codes, sondern der Analyse und des Nachdenkens über die sinnvollste Vorgehensweise, daran ändert die KI nichts. Sie lässt sich nutzen, um Informationen zusammen zu tragen, aber die „manuelle" Denkarbeit darüber, wie die Schritte aussehen auf dem Weg zum neuen System, die bleibt. Zumindest beim aktuellen Stand würde ich es keiner KI überlassen, im Alleingang einen Migrationsplan zu erstellen.

## Wo die KI jedoch sehr nützlich wird

... sind die Teile, in denen es direkt um Code geht. Dabei übernimmt sie am Anfang ein wenig die Rolle eines Junior-Partners im Pair Programming. Wir waren ein variables Team mit drei Leuten (wie gesagt, es geht um Weiterbildung zwischen zwei Projekten), und wir hatten nach ca. **20 Stunden (!)** den gesamten Code portiert. Wir haben das nicht einmal gemacht, sondern jeder allein mit der KI auf eine andere Art und Weise. Jeder Ansatz hatte verschiedene Vor- und Nachteile. Aber jeder von uns konnte das System erfolgreich migrieren (mit mehr oder weniger hohen Kosten für die KI).

Frisch ermutigt, wie wir waren, gingen wir gleich an eine größere Aufgabe.

## Lernkurve, 2. Teil: Migration STAR von Spring Boot in Quarkus

STAR ist aktuell in Spring Boot, wir wählten Quarkus als Alternative dazu. Bei STAR reden wir über ca. **100.000 LOC**, der Grundsatz mit dem „überlasse den Plan nicht allein der KI" galt hier erst recht, an dieser Stelle war bereits viel Vorarbeit geleistet und es wurden z.B. verschiedene Spikes vorgeschlagen, wie den, mit den Urlaubsdaten zu beginnen.

Wir haben sehr schnell gesehen, dass die Anlehnung an das klassische Vorgehen -- ich schneide meine Aufgabe in kleine, handelbare Tasks -- auch hier absolut empfehlenswert ist. Denn wir haben verschiedene Dinge gelernt:

### KI braucht Blaupausen

KI arbeitet schon mal nach dem „monkey see, monkey do"-Prinzip, soll heißen, sie kopiert einen Prozess, ohne verstanden zu haben, warum er funktioniert. Copy & Paste führt allerdings bei einem gewissen Prozentsatz zu unbrauchbaren Ergebnissen. Anders gesagt: Der Code, den die KI „einfach so" erstellt hatte, war vielleicht zu 95% korrekt. Aber die restlichen 5% waren für die Tonne.

Also ist **Qualitätssicherung**, beispielsweise mit automatisierten Tests, ein Muss. Leider reicht es auch nicht, die KI zu fragen, ob sie getestet habe, denn die Antwort ist im Zweifelsfall immer ein „ja", trotzdem sind dann Tests rot oder es kompiliert einfach nichts. Automatisierte Tests muss man nach meiner Erfahrung relativ brutal in die KI „hineinprompten".

Um Qualitätsrisiken zu minimieren, haben wir erst einmal einen kleinen Task ausgewählt, etwa 5000 LOC, und die KI bei der Codeerstellung und dem Testing quasi an die Hand genommen wie einen Junior-Partner. Damit entstand eine **Blaupause** für ein korrektes Vorgehen, das die KI gelernt und entsprechend für die anderen Tasks angewendet hat.

### Wenn er überläuft, läuft nichts mehr: Der Kontextspeicher

Der zweite Grund, warum große Aufgaben auch für die KI in kleine gesplittet werden müssen, ist das Limit des Kontextspeichers: KI kann immer nur eine bestimmte Anzahl an Tokens verarbeiten. Diese Anzahl klingt zunächst gigantisch, wird jedoch mit 100.000 LOC definitiv gesprengt. Code verbrennt sozusagen viele Tokens, sobald der Speicher überläuft, wird die KI „dumm" und produziert Unfug.

Das ist z.B. auch häufig bei RAG-Projekten das Problem, wenn eine KI sämtliche Unternehmensdokumente durchforsten soll und der entstehende Information-Overflow zu Fehlern führt. Da hilft es, eine intelligente Suchfunktion (RAG) vorzuschalten. In unserem Projekt haben wir den Weg gewählt, die Aufgabe in viele kleine Tasks zu schneiden.

### Habe ich das jetzt gemacht oder nicht -- von der Notwendigkeit des Task Masters

Wenn ich viele Tasks habe, geht schnell der Überblick verloren, was davon schon gemacht wurde und was nicht. Wir haben unter anderem [Task Master](https://www.task-master.dev) benutzt, um eine Liste aller Tasks inklusive Checkboxen zu erhalten, in der erledigte Tasks einfach abgehakt wurden. Andernfalls fängt die KI auch gerne mal an zu fabulieren und setzt Dinge auf „done", die sie noch nicht einmal begonnen hat.

## Okay, und wozu jetzt der ganze Aufwand?

In einem Wort: **Geschwindigkeit**.

Nein, KI ist Stand heute in einem Software-Migrations-Projekt kein Selbstläufer. Sie muss die Grundlagen des sauberen Engineerings lernen (Testautomatisierung!), sie nimmt uns nicht ab, sinnvolle Pläne zu machen. Außerdem gerät sie ab und zu durcheinander, was sie getan hat und was nicht. Aber das sind alles Dinge, die man ihr beibringen kann. Vor allem sind es Dinge, die wir andrenas ihr beibringen können, und das vermutlich besser als die meisten. Denn das sind typische Qualitätskriterien, nach denen wir arbeiten und schon immer gearbeitet haben.

Sobald wir die KI fit gemacht haben, macht sie uns schneller, mindestens um den Faktor 2, weil sie sozusagen als weitere*r Entwickler*in agiert. Oft ist der Tempo-Zuwachs aber noch viel höher. Nehmen wir das STAR Projekt: Für eine Backend-Migration hätte ich bisher ca. 6 Monate veranschlagt. Jetzt liegt meine Einschätzung eher bei **6 Wochen!**

Damit werden wir andrenas für unsere Kunden in zweierlei Hinsicht attraktiver: Erstens, weil wir effizienter sind. Dabei reden wir nicht von „ein wenig effizienter" oder „unter Umständen könnte es sein, dass". Wir reden, siehe STAR Projekt, von **6 Wochen statt von 6 Monaten**, bei einem Team, das gerade erst angefangen hat, sich mit KI-gestützter professioneller Entwicklung zu befassen.

Zweitens sind die meisten Migrations- alias Modernisierungsprojekte sehr, sehr groß (Millionen LOC) und dementsprechend ein finanzielles Wagnis. Vermutlich ist es für viele Kunden eine verlockende Option, erstmal einen Durchstich mit einem KI-Projekt zu machen und danach anhand von Fakten entscheiden zu können, wie sie weiter vorgehen.

Deshalb lohnt es sich auf jeden Fall für jede*n von uns, sich in die KI-gestützte Entwicklung einzuarbeiten. Zumal sie sich wunderbar kombinieren lässt mit anderen schönen Dingen wie Cloud oder Microservices oder beliebten Praktiken wie denen, Anwendungen in Docker laufen zu lassen.

## Und was kann ich jetzt tun?

Eventuelle projektfreie Zeit nutzen, um dich in KI einzuarbeiten. Dazu setzen wir verschiedene Optionen auf, damit du möglichst schnell und zielgerichtet vorgehen kannst.

> **Tipp:** Die meisten installieren direkt die KI-Tools (wie Claude Code oder Kilo Code) auf ihrem Rechner. Und in der Regel ist das auch ok. Aber es gibt immer ein gewisses Restrisiko, dass die KI etwas falsch macht und z.B. die falschen Daten / Verzeichnisse löscht. Um hier auf Nummer sicher zu gehen, empfehle ich dir, auch gleich das Thema **Dev Container** anzuschauen.""",
        "tags": ["ki", "migration", "workshop"],
        "comments": [],
    },
]


def _upsert_user(User, *, username, email, password, image):
    user = User.objects.filter(username=username).first()
    if user is None:
        user = User.objects.create(
            username=username,
            email=email,
            password=make_password(password),
            image=image,
        )
        return user

    update_fields = []
    if user.email != email:
        user.email = email
        update_fields.append("email")
    if not check_password(password, user.password):
        user.password = make_password(password)
        update_fields.append("password")
    if user.image != image:
        user.image = image
        update_fields.append("image")

    if update_fields:
        user.save(update_fields=update_fields)
    return user


def seed_workshop_content(apps, schema_editor):
    User = apps.get_model("users", "User")
    Tag = apps.get_model("articles", "Tag")
    Article = apps.get_model("articles", "Article")
    Comment = apps.get_model("articles", "Comment")

    test_user = _upsert_user(
        User,
        username=TEST_USERNAME,
        email=TEST_EMAIL,
        password=TEST_PASSWORD,
        image=TEST_IMAGE,
    )
    author_user = _upsert_user(
        User,
        username=JW_USERNAME,
        email=JW_EMAIL,
        password=JW_PASSWORD,
        image=JW_IMAGE,
    )

    tag_cache = {}
    for article_seed in ARTICLE_SEEDS:
        for tag_name in article_seed["tags"]:
            if tag_name in tag_cache:
                continue

            tag_slug = slugify(tag_name)
            tag, _ = Tag.objects.get_or_create(
                name=tag_name,
                defaults={"slug": tag_slug},
            )
            if tag.slug != tag_slug:
                tag.slug = tag_slug
                tag.save(update_fields=["slug"])
            tag_cache[tag_name] = tag

    for article_seed in ARTICLE_SEEDS:
        title = article_seed["title"]
        article_slug = slugify(title)
        article, _ = Article.objects.get_or_create(
            title=title,
            defaults={
                "slug": article_slug,
                "description": article_seed["description"],
                "body": article_seed["body"],
                "author": author_user,
            },
        )

        update_fields = []
        if article.slug != article_slug:
            article.slug = article_slug
            update_fields.append("slug")
        if article.description != article_seed["description"]:
            article.description = article_seed["description"]
            update_fields.append("description")
        if article.body != article_seed["body"]:
            article.body = article_seed["body"]
            update_fields.append("body")
        if article.author_id != author_user.id:
            article.author = author_user
            update_fields.append("author")

        if update_fields:
            article.save(update_fields=update_fields)

        article.tag_list.set([tag_cache[tag] for tag in article_seed["tags"]])
        article.favored_by.add(test_user)

        for comment_text in article_seed["comments"]:
            Comment.objects.get_or_create(
                article=article,
                author=test_user,
                body=comment_text,
            )


def unseed_workshop_content(apps, schema_editor):
    User = apps.get_model("users", "User")
    Tag = apps.get_model("articles", "Tag")
    Article = apps.get_model("articles", "Article")

    titles = [article_seed["title"] for article_seed in ARTICLE_SEEDS]
    tag_names = {
        tag_name
        for article_seed in ARTICLE_SEEDS
        for tag_name in article_seed["tags"]
    }

    Article.objects.filter(title__in=titles).delete()
    for tag_name in tag_names:
        tag = Tag.objects.filter(name=tag_name).first()
        if tag and not tag.articles.exists():
            tag.delete()

    User.objects.filter(username=TEST_USERNAME, email=TEST_EMAIL).delete()
    User.objects.filter(username=JW_USERNAME, email=JW_EMAIL).delete()


class Migration(migrations.Migration):
    dependencies = [
        (
            "articles",
            "0002_alter_article_slug_alter_article_tag_list_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(seed_workshop_content, unseed_workshop_content),
    ]
